### ISSUE TITLE
Emergency Response Web UI Widget

### ISSUE THREAD

**Issue by dan-du-car** [usdot-fhwa-stol/carma-messenger#173]
### Summary

A new Web UI widget is required to provide a frontend for the user to interact with the backend emergency_response_vehicle_plugin node in CARMA Messenger. This Web UI widget will subscribe to /bsm_outbound topic and display the following ERV data:

This ERV’s static ID.

Vehicle Position (latitude and longitude)

Vehicle Velocity

Emergency Sirens Status

Emergency Lights Status

This UI will subscribe to messages on the /emergency_vehicle_ui_warning topic to receive any warning messages from downstream vehicles that are unable to change lanes out of the path of this ERV. The UI will create and display a warning notification to the user using the string included in the received message (carma_msgs/UIInstructions.msg).

On the UI, there will be an “Arrived at Emergency Location” button. If the user clicks this button, the UI will transition to the ‘Event Management’ UI Widget developed for the Traffic Incident Management (TIM) Use Case, so that the user can generate a geofence around their stopping location.

### Reasoning for new functionality

ERV use case

**Comment by JonSmet** [comment]
Issue is closed by merging CARMA Messenger PR #172.
