### ISSUE TITLE
No support for converting and sending a SensorDataSharingMessage (SDSM) between J3224 and CARMA messages

### ISSUE THREAD

**Issue by willjohnsonk** [usdot-fhwa-stol/carma-messenger#205]
### Summary

While there have been message definitions created in the J3224/CARMA SensorDataSharingMessage format, there is no convertor to bridge the two. A SDSM convertor should be created in the J2735 convertor node namespace to match existing convertors for BSM, PSM, etc. Additionally, these messages should be properly encoded/decoded for transmission.

### Reasoning for new functionality

SDSM messages will be used in future V2X applications

**Comment by JonSmet** [comment]
Closed after merging #210
